### ISSUE TITLE
Getting error while building the docker image. Please help

### ISSUE THREAD

**Issue by Anubhawn** [qingyanjiu/auto-login-wetty-in-docker#1]
Getting error while Building image file. Could you please guide me.

:~/git/autologin/auto-login-wetty-in-docker$ sudo docker build -t wettyimage/mywetty .
Sending build context to Docker daemon 904.2 kB
Step 1/23 : FROM node
latest: Pulling from library/node
d660b1f15b9b: Pull complete
46dde23c37b3: Pull complete
6ebaeb074589: Pull complete
e7428f935583: Pull complete
eda527043444: Pull complete
f3088daa8887: Pull complete
50db09495eb5: Pull complete
51810167f4e9: Pull complete
Digest: sha256:576446f0ea880126f39392c492ff449a8cf3903530ac57a3a1d84494a6cc2a64
Status: Downloaded newer image for node:latest
 ---> b064644cf368
Step 2/23 : ADD . /app
 ---> d01124a0788b
Removing intermediate container 11c4d132b681
Step 3/23 : WORKDIR /app
 ---> 7c1cd9a0e208
Removing intermediate container 236c33d3a15f
Step 4/23 : RUN npm install
 ---> Running in 49a54a3b7ea4
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated connect@2.14.1: connect 2.x series is deprecated
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated static-favicon@1.0.0: use serve-favicon module

> pty.js@0.3.1 install /app/node_modules/pty.js
> node-gyp rebuild

make: Entering directory '/app/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../../nan/nan.h:190:0,
                 from ../src/unix/pty.cc:20:
../../nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../../nan/nan_maybe_43_inl.h:88:15: error: 'class v8::Object' has no member named 'ForceSet'
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^
In file included from ../src/unix/pty.cc:20:0:
../../nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)':
../../nan/nan.h:817:60: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/10.9.0/include/node/node.h:171): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
../../nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)':
../../nan/nan.h:831:62: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/10.9.0/include/node/node.h:164): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
../../nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)':
../../nan/nan.h:845:62: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/10.9.0/include/node/node.h:157): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
../../nan/nan.h: In member function 'v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const':
../../nan/nan.h:1463:5: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/10.9.0/include/node/node.h:171): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
../src/unix/pty.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)':
../src/unix/pty.cc:164:45: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated (declared at /root/.node-gyp/10.9.0/include/node/v8.h:2874): Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value file(info[0]->ToString());
                                             ^
../src/unix/pty.cc:175:71: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated (declared at /root/.node-gyp/10.9.0/include/node/v8.h:2874): Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value arg(argv_->Get(Nan::New<Integer>(i))->ToString());
                                                                       ^
../src/unix/pty.cc:186:71: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated (declared at /root/.node-gyp/10.9.0/include/node/v8.h:2874): Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value pair(env_->Get(Nan::New<Integer>(i))->ToString());
                                                                       ^
../src/unix/pty.cc:191:45: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated (declared at /root/.node-gyp/10.9.0/include/node/v8.h:2874): Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value cwd_(info[3]->ToString());
                                             ^
../src/unix/pty.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE PtyGetProc(Nan::NAN_METHOD_ARGS_TYPE)':
../src/unix/pty.cc:371:45: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated (declared at /root/.node-gyp/10.9.0/include/node/v8.h:2874): Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value tty_(info[1]->ToString());
                                             ^
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
pty.target.mk:101: recipe for target 'Release/obj.target/pty/src/unix/pty.o' failed
make: Leaving directory '/app/node_modules/pty.js/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.4.0-133-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/pty.js
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-17T00_32_44_744Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1

**Comment by qingyanjiu** [comment]
Hi Anubhawn, this issue might be related to the node version of image, I've updated the Dockerfile, pls try to build again.

<a href="https://github.com/qingyanjiu/auto-login-wetty-in-docker/commit/311dfce777cd808a5101e806ff2a9b5e43b8f38c">Update detail</a>

**Comment by Anubhawn** [comment]
Thanks qingyanjiu.
